version : "3.3"

services:
 mysqldb:
  container_name: mysql
  image: mysql:5.7
  restart: unless-stopped
  environment:
   MYSQL_ROOT_PASSWORD: selim
  volumes:
    - /home/mysqldata:/var/lib/mysql
 project1_app:
  image: selimdeniz/selimdeniz-5gamix-g5-projet1:1.0.0
  container_name: mycontainer
  tty: true
  ports:
   - 8089:8089
  depends_on:     
   - mysqldb