version : "3.3"

services:
 mysqldb:
  container_name: mysqldb1
  image: mysql:latest
  restart: unless-stopped
  environment:
   MYSQL_ROOT_PASSWORD: selim
  volumes:
    - /home/mysqldata:/var/lib/mysql
 spring_app:
  image: selimdeniz/springapp
  container_name: spring1
  restart: on-failure
  ports:
   - 8089:8089
  depends_on:     
   - mysqldb